language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

# cache vendor dirs
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer update --dev --prefer-dist --no-interaction

before_script:
  - mysql -e 'create database yuncms_system_test;'

script:
  - phpunit --coverage-clover=coverage.clover

